#!/usr/bin/env bash
# make all data URLs local (for testing)
if [ ! -f dashboards/reportcard.json.tmp ]; then
	mv dashboards/reportcard.json dashboards/reportcard.json.tmp
	sed 's/http:\/\/datasets.wikimedia.org\/limn-public-data\/mobile\/datafiles/http:\/\/localhost:5000\/data\/datafiles\/mobile/g' dashboards/reportcard.json.tmp > dashboards/reportcard.json
fi
