#!/usr/bin/env bash
# make all data URLs remote (use before pushing to repo if you used localurl)
for f in `find datasources -name "*.json" -print`; do
  # don't use sed's -i option, it's not cross-platform
  # (http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-and-linux)
  sed 's/\/data\/datafiles\/mobile/http:\/\/stat1001\.wikimedia\.org\/limn-public-data\/mobile\/datafiles/g' "$f" > tmp.json
  mv -f tmp.json "$f"
done

